#服务端容器的配置
server:
  port: 9090


#数据库配置
spring:
  datasource:
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.6.17:3306/cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://111.229.138.120:3306/cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    # JPA配置

    #热部署配置
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
      freemarker:
        cache: false    #页面不加载缓存，修改即时生效
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    # formatSQL得这样写
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai